### ISSUE TITLE
Turn off download database link

### ISSUE THREAD

**Issue by simonw** [simonw/sfms-history#25]
The DB is over 12MB in size, and Vercel has a 4.5MB limit:

https://vercel.com/docs/concepts/limits/overview#serverless-function-payload-size-limit

So the link just doesn't work.

https://sfms-history.vercel.app/sfms

![CleanShot 2022-08-24 at 10 29 12@2x](https://user-images.githubusercontent.com/9599/186484840-b8c00ea3-6b65-4c1e-9d08-eb3d77aa47d3.png)

**Comment by simonw** [comment]
https://sfms-history.vercel.app/sfms is now a 500 error.

```
[ERROR] NameError: name 'false' is not definedTraceback (most recent call last):  File "/var/lang/lib/python3.9/importlib/__init__.py", line 127, in import_module    return _bootstrap._gcd_import(name[level:], package, level)  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked  File "<frozen importlib._bootstrap_external>", line 850, in exec_module  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed  File "/var/task/vc__handler__python.py", line 12, in <module>    __vc_spec.loader.exec_module(__vc_module)  File "<frozen importlib._bootstrap_external>", line 850, in exec_module  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed  File "./index.py", line 27, in <module>    settings={"allow_download": false}Unknown application error occurred
```

**Comment by simonw** [comment]
That fixed it.

https://sfms-history.vercel.app/sfms

<img width="583" alt="image" src="https://user-images.githubusercontent.com/9599/186489842-7c5dfb97-5d41-4215-afef-200b29ebc711.png">
